### ISSUE TITLE
Phi(x,y,z) gives different answers if entire system is shifted

### ISSUE THREAD

**Issue by rowanwalker96** [maroba/multipoles#7]
```
charge_dist = {'discrete': True, 'charges': [{'q': 1, 'xyz': (0, 0, 0.5)}, {'q': -1, 'xyz': (0, 0, -1)}]}
l_max = 3
Phi = MultipoleExpansion(charge_dist, l_max)
Phi(0,0,0)
```
and 
```
charge_dist = {'discrete': True, 'charges': [{'q': 1, 'xyz': (5, 5, 5.5)}, {'q': -1, 'xyz': (5, 5, 4)}]}
l_max = 3
Phi = MultipoleExpansion(charge_dist, l_max)
Phi(5,5,5)
```
give different answers despite being the same arrangement of charges around the evaluation point, is this correct?

**Comment by maroba** [comment]
Well, you have found a bug! In the method `MultipoleExpansion._calc_multipole_coef`, in line 224, it reads

```python
xyz = chg['xyz']
```

But it should be 

```python
xyz = chg['xyz'] - self.center_of_charge
```

If you want you can fix that, add a test and send me a pull request. Then you are one of the contributors. If you don't want or don't have time, no problem, then I can do it.
